name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    name: Build LaTeX document
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: felipe-publio-cv.tex
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          aws-region: auto
      - name: Upload to R2
        run: |
          aws s3 cp felipe-publio-cv.pdf s3://publio-cv/felipe-publio-cv.pdf --endpoint-url https://97f80eebd22b293bea38454d1bfcd003.r2.cloudflarestorage.com/publio-cv
