name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    name: Build LaTeX document
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: felipe-publio-cv.tex
      - name: Upload to Cloudflare R2
        uses: ryand56/r2-upload-action@v1.3.2
        with:
          r2-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: publio-cv
          source-dir: .
          destination-dir: /
